apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hrafnkellos/k8s_argo_infrastructure
    targetRevision: HEAD
    path: addJenking   # Change this to the path you want ArgoCD to sync
  destination:
    server: https://kubernetes.default.svc
    namespace: default         # Change to your target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true