apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hrafnkellos/k8s_argo_infrastructure.git
    targetRevision: HEAD
    path: overlays/test   # Change this to the path you want ArgoCD to sync
  destination:
    server: https://kubernetes.default.svc
    namespace: default         # Change to your target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true