apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Ensures this app is synced first
    argocd.argoproj.io/compare-options: IgnoreExtraneous  # Ignores fields not in git
spec:
  project: default
  source:
    repoURL: https://github.com/Hrafnkellos/k8s_argo_infrastructure.git
    targetRevision: HEAD
    path: overlays/test   # Change this to the path you want ArgoCD to sync
  destination:
    server: https://kubernetes.default.svc
    namespace: default         # Change to your target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false  # Prevents sync if the target directory is empty
    syncOptions:
      - CreateNamespace=true  # Creates namespace if it doesn't exist
      - PruneLast=true  # Ensures resources are pruned last
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  health:
    status: Healthy
    message: "Application is healthy"
  info:
    - name: Description
      value: "Infrastructure deployment for test environment"
    - name: Maintainer
      value: "Hrafnkellos"