# This is a dummy secret (you'll seal it using sealed-secrets) for Argo CD to access Bitbucket.
# (Replace the dummy values with your actual Bitbucket credentials.)
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: "git@bitbucket.org:your-username/your-repo.git"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    (Replace this dummy key with your actual SSH private key (for example, the contents of ~/.ssh/bitbucket_key) )
    -----END OPENSSH PRIVATE KEY----- 