apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.example.com  # This will be overridden by the actual URL
  admin.enabled: "true"
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
  statusbadge.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  configManagementPlugins: |
    - name: kustomize
      init:
        command: [sh, -c]
        args: ["kustomize build"]
      generate:
        command: [sh, -c]
        args: ["kustomize build"]
  repositories: |
    - type: helm
      name: jfrog
      url: https://charts.jfrog.io
    - type: helm
      name: jenkins
      url: https://charts.jenkins.io
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs 