apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - applications
  - repositories
  - ingress.yaml

patches:
  - path: argocd-server-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
