apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Ensure ArgoCD syncs itself first
spec:
  project: default
  source:
    repoURL: https://github.com/Hrafnkellos/k8s_argo_infrastructure
    targetRevision: HEAD
    path: addJenking   # Change this to the path you want ArgoCD to sync
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # ArgoCD should be installed in its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true