apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-oss
  namespace: artifactory
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: artifactory-oss
    repoURL: https://charts.jfrog.io
    targetRevision: 107.111.8  # Latest stable version
    helm:
      releaseName: artifactory-oss
      values: |
        artifactory:
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          persistence:
            storageClass: "local-path"
            size: 20Gi
            mountPath: "/var/opt/jfrog/artifactory"
          nginx:
            enabled: true
            service:
              type: ClusterIP
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
          postgresql:
            enabled: false  # Disable built-in PostgreSQL
          ingress:
            enabled: false  # Enable if you need external access
          systemYaml:
            shared:
              database:
                type: postgresql
                driver: org.postgresql.Driver
                url: jdbc:postgresql://artifactory-postgresql:5432/artifactory
                username: ${POSTGRES_USER}
                password: ${POSTGRES_PASSWORD}
  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 