apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-oss
  namespace: artifactory
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: artifactory-oss
    repoURL: https://charts.jfrog.io
    targetRevision: 107.111.8
    helm:
      releaseName: artifactory-oss
      values: |
        artifactory:
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          persistence:
            storageClass: "local-path"
            size: 20Gi
            mountPath: "/var/opt/jfrog/artifactory"
          nginx:
            enabled: true
            service:
              type: ClusterIP
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
            persistence:
              enabled: true
              storageClass: "local-path"
              size: 1Gi
              mountPath: "/var/opt/jfrog/nginx"
            securityContext:
              enabled: true
              fsGroup: 107
            containerSecurityContext:
              enabled: true
              runAsUser: 103
              runAsNonRoot: true
            initContainers:
              - name: init-chmod-data
                image: busybox
                command: ["sh", "-c", "chown -R 103:107 /var/opt/jfrog/nginx && chmod -R 755 /var/opt/jfrog/nginx"]
                securityContext:
                  runAsUser: 0
                volumeMounts:
                  - name: nginx-data
                    mountPath: /var/opt/jfrog/nginx
              - name: init-create-logs
                image: busybox
                command: ["sh", "-c", "mkdir -p /var/opt/jfrog/nginx/logs && touch /var/opt/jfrog/nginx/logs/error.log /var/opt/jfrog/nginx/logs/access.log && chown -R 103:107 /var/opt/jfrog/nginx/logs && chmod -R 755 /var/opt/jfrog/nginx/logs"]
                securityContext:
                  runAsUser: 0
                volumeMounts:
                  - name: nginx-data
                    mountPath: /var/opt/jfrog/nginx
          postgresql:
            enabled: false
          systemYaml:
            shared:
              database:
                type: postgresql
                driver: org.postgresql.Driver
                url: jdbc:postgresql://artifactory-postgresql:5432/artifactory
                username: ${POSTGRES_USER}
                password: ${POSTGRES_PASSWORD}
  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 