apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-api-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hrafnkellos/k8s_argo_infrastructure
    targetRevision: AddJenking
    path: overlays/test/base/example-api-2
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 