apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.55
    helm:
      values: |
        controller:
          serviceType: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
