apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.55
    helm:
      values: |
        controller:
          serviceType: ClusterIP
          servicePort: 8080
          jenkinsUriPrefix: /jenkins
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
              traefik.ingress.kubernetes.io/router.middlewares: jenkins-strip-prefix
              traefik.ingress.kubernetes.io/router.middlewares.jenkins-strip-prefix.stripprefix.prefixes: /jenkins
              traefik.ingress.kubernetes.io/router.middlewares.jenkins-strip-prefix.stripprefix.forceslash: "false"
            path: /jenkins
            pathType: Prefix
            host: 192.168.45.238
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
