apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-nginx-config
  namespace: artifactory
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-nginx-server-block
  namespace: artifactory
data:
  artifactory.conf: |
    upstream artifactory {
        server artifactory-oss:8081;
    }
    server {
        listen 8080;
        server_name artifactory;
        client_max_body_size 0;
        chunked_transfer_encoding on;
        location / {
            proxy_pass http://artifactory;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    } 