apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-setup-script
  namespace: artifactory
data:
  setup.sh: |
    #!/bin/sh
    set -e

    # Create required directories
    mkdir -p /var/opt/jfrog/nginx/logrotate
    mkdir -p /var/opt/jfrog/nginx/logs
    mkdir -p /var/log/nginx

    # Set ownership
    chown -R 1030:107 /var/opt/jfrog/nginx
    chown -R 1030:107 /var/log/nginx

    # Set permissions
    chmod -R 775 /var/opt/jfrog/nginx
    chmod -R 775 /var/log/nginx

    # Create log files if they don't exist
    touch /var/opt/jfrog/nginx/logs/error.log
    touch /var/opt/jfrog/nginx/logs/access.log
    touch /var/log/nginx/error.log
    touch /var/log/nginx/access.log

    # Set permissions for log files
    chown 1030:107 /var/opt/jfrog/nginx/logs/error.log
    chown 1030:107 /var/opt/jfrog/nginx/logs/access.log
    chown 1030:107 /var/log/nginx/error.log
    chown 1030:107 /var/log/nginx/access.log

    chmod 644 /var/opt/jfrog/nginx/logs/error.log
    chmod 644 /var/opt/jfrog/nginx/logs/access.log
    chmod 644 /var/log/nginx/error.log
    chmod 644 /var/log/nginx/access.log

    echo "Nginx directory setup completed successfully" 