apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  # sealed-bitbucket-repo.yaml removed, now environment-specific 
  # look in overlays for repository files