replicaCount: 3

image:
  repository: my-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  enabled: true
  annotations: {}
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: true
  pathType: Prefix
  hosts:
    - host: production.example.com
      paths:
        - /
  tls:
    - secretName: production-tls
      hosts:
        - production.example.com

nodeSelector: {}

tolerations: []

affinity: {}