apiVersion: v1
kind: Secret
metadata:
  name: artifactory-postgresql
  namespace: artifactory
type: Opaque
stringData:
  postgresql-password: "change-me-in-production"  # This will be encrypted by kubeseal 