apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml

labels:
  - pairs:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: jenkins
      app.kubernetes.io/component: jenkins-controller
    includeSelectors: true
    includeTemplates: true 