apiVersion: v1
kind: Service
metadata:
  name: example-api-service
  namespace: demo
spec:
  selector:
    app: example-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678