apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: rl-postgres-db
          image: postgres:15
          resources:
            requests:
              memory: "512Mi"
#              cpu: "2m"
#            limits:
#              memory: "32Mi"
#              cpu: "50m"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: postgres-config-map
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
          
