apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: postgres-server
spec:
  selector:
    app: postgres-db
  type: LoadBalancer
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432