apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloak
type: Opaque
data:
  keycloak-admin-password: cGFzc3dvcmQ= # echo -n 'password' | base64 
  keycloak-db-password: cGFzc3dvcmQ= # echo -n 'password' | base64 
  # this file should be changed to a bitnami sealed secret 